name: a_crave
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.13.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  sizer: ^2.0.15
  pin_code_fields: ^7.4.0
  intl_phone_field: ^3.0.0
  splash_screen_view: ^3.0.0
  dotted_border: ^2.0.0+2
  country_code_picker: ^2.0.2
  story_view: ^0.13.2
  circle_list: ^1.0.2
  google_maps_flutter: ^2.0.9
  visibility_detector: ^0.2.2
  camera: ^0.8.1+7
  video_player: ^2.2.3
  path_provider: ^2.0.2
  permission_handler: 8.0.1
  expandable: ^5.0.1
  device_info_plus: ^4.0.0
  cupertino_back_gesture: ^0.1.0
  introduction_screen: ^3.0.1
  flutter_slidable: ^1.3.2
  shared_preferences: ^2.0.7
  geolocator: ^8.0.0
  geocoding: ^2.0.5
  image_picker: ^0.8.4+1
  pinch_zoom: ^1.0.0
  fluttertoast: ^8.0.9
  record_mp3: ^3.0.0
  audioplayers: ^0.20.1
  tflite: ^1.1.2
  google_place: ^0.4.7
  maps_launcher: ^2.0.1
  url_launcher: ^6.0.10
  flutter_vibrate: ^1.3.0
  text_editor: ^0.7.0
#  custom_marker: ^1.0.0
#  flutter_haptic: ^0.0.3
#  firebase_core: ^1.12.0
#  firebase_messaging: ^11.2.7
#  firebase_core_platform_interface: 4.2.4
#  firebase_messaging_platform_interface: ^3.2.0
#  firebase_auth_platform_interface: ^6.1.11


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/tflite/food_classifier.tflite
    - assets/tflite/labels.txt
    - assets/tflite/mobilenet_v1_1.0_224.tflite
    - assets/tflite/labels2.txt
    - images/splashscreen.jpg
    - images/splashscreen2.jpg
    - images/crave_word.jpg
    - images/logo_twitter.png
    - images/logo_google.png
    - images/logo_facebook.png
    - images/logo_apple.png
    - images/user.png
    - images/round_bg.png
    - images/menu_camera.png
    - images/menu_chat.png
    - images/menu_cravings.png
    - images/menu_home.png
    - images/menu_me.png
    - images/menu_reels.png
    - images/menu_run_ads.png
    - images/menu_settings.png
    - images/menu_switch_account.png
    - images/menu_bell.png
    - images/sidewheel.png
    - images/crave_logo_word.png
    - images/crave_logo.jpg
    - images/food1.png
    - images/food2.png
    - images/food3.png
    - images/food4.png
    - images/icon_crave.png
    - images/icon_love.png
    - images/reels1.png
    - images/reels2.png
    - images/profile_img.png
    - images/comment_icon.png
    - images/forward_icon.png
    - images/others_icon.png
    - images/user1.png
    - images/verified_logo.png
    - images/love_selected_icon.png
    - images/location_icon.png
    - images/subComments.png
    - images/stories_share.png
    - images/reelsList1.png
    - images/reelsList2.png
    - images/reelsList3.png
    - images/reelsList4.png
    - images/reelsList5.png
    - images/reelsList6.png
    - images/overlay_reels.png
    - images/icon_music.png
    - images/menu_burger.png
    - images/icon_chat_camera.png
    - images/icon_chat_img.png
    - images/icon_chat_mic.png
    - images/icon_chat_send.png
    - images/comment_icon_fill.png
    - images/profile_bg.png
    - images/mcdlogo.jpg
    - images/burger1.png
    - images/burger2.jpg
    - images/mcdfries.jpg
    - images/mcdicecream.jpg
    - images/mcdcafe.jpg
    - images/business_bg.png
    - images/menu_manage_business.png
    - images/menu_manage_branches.png
    - images/menu_manage_access.png
    - images/cancel_btn_icon.png
    - images/add_menu_from_camera.png
    - images/add_menu_from_gallery.png
    - images/add_menu_from_menu.png
    - images/add_team_member_icon.png
    - images/crave_credit_icon.png
    - images/icon_location_camera.png
    - images/icon_select_img.png
    - images/icon_flip_camera.png
    - images/icon_capture_img.png
    - images/icon_filter.png
    - images/icon_text.png
    - images/camera_wheel_bg.png
    - images/user_square1.png
    - images/user_square2.png
    - images/user_square3.png
    - images/food_cravings1.png
    - images/food_cravings2.png
    - images/food_cravings3.png
    - images/food_cravings4.png
    - images/food_cravings5.png
    - images/round_bg_2.png
    - images/homepage_tutorial1.png
    - images/homepage_tutorial2.png
    - images/homepage_tutorial3.jpg
    - images/homepage_tutorial4.jpg
    - images/own_profile_bg.png
    - images/own_profile_bg2.png
    - images/own_profile_bg3.png
    - images/own_profile_bg4.png
    - images/single_grid_icon.png
    - images/single_grid_icon_selected.png
    - images/grid_icon_selected.png
    - images/grid_icon.png
    - images/edit_cravelist_name.png
    - images/craves_list_icon.png
    - images/post_icon.png
    - images/icon_edit_feed.png
    - images/icon_delete_feed.png
    - images/icon_crave_grey.png
    - images/icon_no_audio.png
    - images/icon_add_to_crave.png
    - images/icon_not_interested.png
    - images/icon_report_not_food.png
    - images/gmaps_icon.png
    - images/waze_icon.png
    - video/splashvideo.mp4

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: font/Montserrat-Regular.ttf
        - asset: font/Montserrat-Bold.ttf
          weight: 700
        - asset: font/Montserrat-SemiBold.ttf
          weight: 600
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
splash_screen_view:
  # Use color to set the background of your splash screen to a solid color.
  # Use background_image to set the background of your splash screen to a png image.
  # This is useful for gradients. The image will be stretch to the  size of the app.
  # Only one parameter can be used, color and background_image cannot both be set.

  color: "#ffffff"